#!/usr/bin/with-contenv bash

if [ ! -d "/app/hackerspace" ]; then
    git clone https://github.com/obscuritysystems/hackerspace/ /app/
fi

if [ ! -L "/app/hackerspace/settings.py" ]; then
    ln -s /config/settings.py /app/hackerspace/settings.py
fi

if [ ! -f "/config/settings.py" ]; then
    cp /defaults/settings.py /config/settings.py
fi